name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        run: |
          npm ci
          npm run build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
