name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      name: Checkout code
      uses: actions/checkout@v2
      with:
        runs-on: ubuntu-latest
        node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install -g gh-pages

      - name: Build and deploy
        run: |
          npm run build
          gh-pages -d public -b gh-pages
